"use client";

/**
 * "Show the exact email that went out" (SPEC §6.4).
 *
 * Fetches the *stored* rendered message rather than re-rendering the template. That distinction
 * is the whole point: "here is exactly what your patient received" is a far stronger claim than
 * "here is roughly what we would send now", and it is the honest answer when a clinic asks.
 *
 * The HTML is displayed inside a sandboxed iframe. Two reasons, and the second matters more:
 *
 * 1. Email HTML is full of tables and inline styles that would inherit and fight with the
 *    application's own CSS. An iframe gives it its own document, so it renders as a mail client
 *    would show it.
 * 2. `sandbox` with no `allow-scripts` means nothing in that markup can execute. The content is
 *    generated by our own template today, but a message body is exactly the kind of field that
 *    later becomes configurable — and rendering it unsandboxed would then be a self-inflicted
 *    cross-site scripting hole in the staff interface.
 */

import * as React from "react";

import { Spinner } from "@/components/ui/primitives";
import { toDisplayMessage, useApi } from "@/lib/use-api";
import type { RenderedMessage } from "@/lib/patients";

export function MessagePreview({
  patientPublicId,
  reminderId,
  subject,
}: {
  patientPublicId: string;
  reminderId: string;
  subject: string;
}) {
  const api = useApi();
  const [open, setOpen] = React.useState(false);
  const [message, setMessage] = React.useState<RenderedMessage | null>(null);
  const [loading, setLoading] = React.useState(false);
  const [error, setError] = React.useState<string | null>(null);

  // Fetched on first open rather than with the timeline. A rendered email is several kilobytes,
  // and a patient with twelve reminders would otherwise ship all twelve to draw a list nobody
  // has asked to expand.
  async function toggle() {
    const next = !open;
    setOpen(next);

    if (next && message === null && !loading) {
      setLoading(true);
      setError(null);
      try {
        setMessage(
          await api.get<RenderedMessage>(
            `/patients/${patientPublicId}/reminders/${reminderId}/message`,
          ),
        );
      } catch (caught) {
        setError(toDisplayMessage(caught));
      } finally {
        setLoading(false);
      }
    }
  }

  return (
    <div className="mt-2">
      <button
        type="button"
        onClick={toggle}
        aria-expanded={open}
        className="rounded-control text-xs font-medium text-brand hover:underline focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand"
      >
        {open ? "Hide the email that was sent" : "View the email that was sent"}
      </button>

      {open ? (
        <div className="mt-2 overflow-hidden rounded-control border border-border">
          <p className="border-b border-border bg-canvas px-3 py-2 text-xs text-ink-muted">
            <span className="font-medium text-ink">Subject:</span> {subject}
          </p>

          {loading ? (
            <p className="flex items-center gap-2 px-3 py-6 text-xs text-ink-muted">
              <Spinner /> Loading the message…
            </p>
          ) : error ? (
            <p className="px-3 py-4 text-xs text-danger">{error}</p>
          ) : message?.html ? (
            <iframe
              title={`Reminder email: ${subject}`}
              srcDoc={message.html}
              // No allow-scripts, no allow-same-origin: the message renders and can do nothing
              // else. See the note at the top of this file.
              sandbox=""
              className="h-80 w-full bg-white"
            />
          ) : (
            <pre className="max-h-80 overflow-auto whitespace-pre-wrap px-3 py-3 text-xs text-ink-muted">
              {message?.text ?? "This message was not stored."}
            </pre>
          )}
        </div>
      ) : null}
    </div>
  );
}
