"""initial schema

Revision ID: 46d923e0d3c8
Revises:
Created: 2026-08-16 21:37:33.673687+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# Revision identifiers, used by Alembic to order migrations.
revision: str = "46d923e0d3c8"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organizations")),
    )
    op.create_index(op.f("ix_organizations_slug"), "organizations", ["slug"], unique=True)
    op.create_table(
        "clinic_settings",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("clinic_name", sa.String(length=200), nullable=False),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("website", sa.String(length=500), nullable=True),
        sa.Column("scheduling_url", sa.String(length=500), nullable=True),
        sa.Column(
            "timezone", sa.String(length=64), server_default="America/Los_Angeles", nullable=False
        ),
        sa.Column(
            "annual_interval_months", sa.Integer(), server_default=sa.text("12"), nullable=False
        ),
        sa.Column(
            "estimated_annual_visit_value",
            sa.Numeric(precision=10, scale=2),
            server_default=sa.text("250.00"),
            nullable=False,
        ),
        sa.Column("reminder_signature", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "annual_interval_months > 0 AND annual_interval_months <= 60",
            name=op.f("ck_clinic_settings_annual_interval_months_range"),
        ),
        sa.CheckConstraint(
            "estimated_annual_visit_value >= 0",
            name=op.f("ck_clinic_settings_estimated_annual_visit_value_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_clinic_settings_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("organization_id", name=op.f("pk_clinic_settings")),
    )
    op.create_table(
        "patients",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("public_id", sa.String(length=12), nullable=False),
        sa.Column("external_id", sa.String(length=100), nullable=True),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column(
            "preferred_contact_method",
            sa.Enum("EMAIL", "SMS", "PHONE", name="preferred_contact_method"),
            nullable=False,
        ),
        sa.Column("last_annual_visit_date", sa.Date(), nullable=False),
        sa.Column("next_annual_due_date", sa.Date(), nullable=False),
        sa.Column("scheduled_for", sa.Date(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "DUE_SOON",
                "DUE",
                "OVERDUE",
                "SCHEDULED",
                "COMPLETED",
                "INACTIVE",
                name="patient_status",
            ),
            nullable=False,
        ),
        sa.Column(
            "reminders_enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column("opted_out_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_patients_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_patients")),
    )
    op.create_index(
        "ix_patients_organization_id_next_annual_due_date",
        "patients",
        ["organization_id", "next_annual_due_date"],
        unique=False,
    )
    op.create_index(
        "ix_patients_organization_id_status",
        "patients",
        ["organization_id", "status"],
        unique=False,
    )
    op.create_index(op.f("ix_patients_public_id"), "patients", ["public_id"], unique=True)
    op.create_index(
        "uq_patients_organization_id_external_id",
        "patients",
        ["organization_id", "external_id"],
        unique=True,
        postgresql_where=sa.text("external_id IS NOT NULL"),
    )
    op.create_index(
        "uq_patients_organization_id_lower_email",
        "patients",
        ["organization_id", sa.literal_column("lower(email)")],
        unique=True,
    )
    op.create_table(
        "reminder_rules",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "key",
            sa.Enum("T_MINUS_30", "T_MINUS_7", "T_ZERO", "T_PLUS_30", name="reminder_rule_key"),
            nullable=False,
        ),
        sa.Column("days_relative_to_due_date", sa.Integer(), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "template_id", sa.String(length=100), server_default="annual_recall", nullable=False
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_reminder_rules_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reminder_rules")),
        sa.UniqueConstraint("organization_id", "key", name="uq_reminder_rules_organization_id_key"),
    )
    op.create_index(
        op.f("ix_reminder_rules_organization_id"),
        "reminder_rules",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "users",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("auth_user_id", sa.UUID(), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("role", sa.Enum("ADMIN", "STAFF", name="user_role"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_users_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_auth_user_id"), "users", ["auth_user_id"], unique=True)
    op.create_index(op.f("ix_users_organization_id"), "users", ["organization_id"], unique=False)
    op.create_table(
        "activity_events",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("actor_user_id", sa.UUID(), nullable=True),
        sa.Column(
            "type",
            sa.Enum(
                "PATIENT_IMPORTED",
                "PATIENT_CREATED",
                "PATIENT_UPDATED",
                "REMINDER_SENT",
                "REMINDER_DELIVERED",
                "REMINDER_FAILED",
                "APPOINTMENT_SCHEDULED",
                "ANNUAL_VISIT_COMPLETED",
                "REMINDERS_PAUSED",
                "PATIENT_OPTED_OUT",
                "SETTINGS_UPDATED",
                name="activity_event_type",
            ),
            nullable=False,
        ),
        sa.Column("subject_patient_id", sa.UUID(), nullable=True),
        sa.Column(
            "payload", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_activity_events_actor_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_activity_events_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["subject_patient_id"],
            ["patients.id"],
            name=op.f("fk_activity_events_subject_patient_id_patients"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_activity_events")),
    )
    op.create_index(
        "ix_activity_events_organization_id_created_at",
        "activity_events",
        ["organization_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_activity_events_organization_id_type",
        "activity_events",
        ["organization_id", "type"],
        unique=False,
    )
    op.create_index(
        "ix_activity_events_subject_patient_id",
        "activity_events",
        ["subject_patient_id"],
        unique=False,
    )
    op.create_table(
        "reminder_events",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("patient_id", sa.UUID(), nullable=False),
        sa.Column("reminder_rule_id", sa.UUID(), nullable=True),
        sa.Column(
            "source", sa.Enum("RULE", "MANUAL", "TEST", name="reminder_source"), nullable=False
        ),
        sa.Column("due_date_snapshot", sa.Date(), nullable=False),
        sa.Column("channel", sa.Enum("EMAIL", "SMS", name="reminder_channel"), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "SCHEDULED",
                "SENDING",
                "SENT",
                "DELIVERED",
                "FAILED",
                "CANCELLED",
                name="reminder_event_status",
            ),
            nullable=False,
        ),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("provider_message_id", sa.String(length=255), nullable=True),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column("rendered_subject", sa.String(length=500), nullable=True),
        sa.Column("rendered_body_html", sa.Text(), nullable=True),
        sa.Column("rendered_body_text", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_reminder_events_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
            name=op.f("fk_reminder_events_patient_id_patients"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["reminder_rule_id"],
            ["reminder_rules.id"],
            name=op.f("fk_reminder_events_reminder_rule_id_reminder_rules"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reminder_events")),
    )
    op.create_index(
        "ix_reminder_events_organization_id_created_at",
        "reminder_events",
        ["organization_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_reminder_events_organization_id_status",
        "reminder_events",
        ["organization_id", "status"],
        unique=False,
    )
    op.create_index(
        "ix_reminder_events_patient_id_created_at",
        "reminder_events",
        ["patient_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "uq_reminder_events_patient_rule_due_date",
        "reminder_events",
        ["patient_id", "reminder_rule_id", "due_date_snapshot"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_reminder_events_patient_rule_due_date", table_name="reminder_events")
    op.drop_index("ix_reminder_events_patient_id_created_at", table_name="reminder_events")
    op.drop_index("ix_reminder_events_organization_id_status", table_name="reminder_events")
    op.drop_index("ix_reminder_events_organization_id_created_at", table_name="reminder_events")
    op.drop_table("reminder_events")
    op.drop_index("ix_activity_events_subject_patient_id", table_name="activity_events")
    op.drop_index("ix_activity_events_organization_id_type", table_name="activity_events")
    op.drop_index("ix_activity_events_organization_id_created_at", table_name="activity_events")
    op.drop_table("activity_events")
    op.drop_index(op.f("ix_users_organization_id"), table_name="users")
    op.drop_index(op.f("ix_users_auth_user_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_reminder_rules_organization_id"), table_name="reminder_rules")
    op.drop_table("reminder_rules")
    op.drop_index("uq_patients_organization_id_lower_email", table_name="patients")
    op.drop_index(
        "uq_patients_organization_id_external_id",
        table_name="patients",
        postgresql_where=sa.text("external_id IS NOT NULL"),
    )
    op.drop_index(op.f("ix_patients_public_id"), table_name="patients")
    op.drop_index("ix_patients_organization_id_status", table_name="patients")
    op.drop_index("ix_patients_organization_id_next_annual_due_date", table_name="patients")
    op.drop_table("patients")
    op.drop_table("clinic_settings")
    op.drop_index(op.f("ix_organizations_slug"), table_name="organizations")
    op.drop_table("organizations")
    # ### end Alembic commands ###

    # Drop the native enum types.
    #
    # Alembic's autogenerate creates enum types on the way up but does NOT drop them on the way
    # down — it only emits DROP TABLE. Without the statements below, `alembic downgrade base`
    # leaves eight orphaned types behind, and the next `alembic upgrade head` fails with
    # `type "preferred_contact_method" already exists`.
    #
    # That makes the downgrade path a one-way door, which is exactly the situation you do not
    # want to discover while trying to rebuild a database under time pressure.
    for enum_name in (
        "user_role",
        "patient_status",
        "preferred_contact_method",
        "reminder_rule_key",
        "reminder_channel",
        "reminder_source",
        "reminder_event_status",
        "activity_event_type",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
